### ISSUE TITLE
你好，看你接收消息源码部分应该是参考鬼手写的，如果长时间运行，有没有Buffer too small异常抛出？

### ISSUE THREAD

**Issue by shangdev** [Greatfar/WeChatHelper#1]
![image](https://user-images.githubusercontent.com/15621520/180343107-dccda9c4-280c-46c0-b624-a36f36dda11d.png)

**Comment by Greatfar** [comment]
这个是因为接收消息的结构体消息内容长度不够，微信服务器有时候发过来的消息超过了定义的结构体长度，只有收到特定消息才会触发，已经被我修复了
